export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';
export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM';
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const ADD_CART_ITEM1 = "ADD_CART_ITEM1";
export const ADD_CART_ITEM2 = "ADD_CART_ITEM2";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL"
export const CHANGE_IMAGE = "CHANGE_IMAGE"
export const ADD_MATERIAL = "ADD_MATERIAL"
export const REMOVE_MATERIAL = "REMOVE_MATERIAL"
export const CHANGE_SAUCE = "CHANGE_SAUCE"
export const REMOVE_CART_ITEM1= "REMOVE_CART_ITEM1"
export const REMOVE_CART_ITEM2= "REMOVE_CART_ITEM2"

 